name: Acorn Login
description: Logs in to an Acorn registry
author: 'Acorn Labs, Inc.'
inputs:
  registry:
    description: 'Registry server address'
    required: true
  username:
    description: 'Username'
    required: true
  password:
    description: Password
    required: true
  local:
    description: "Adds the `--local-storage` argument to `acorn login` if set to 'true'"
    required: false
    default: 'false'
runs:
  using: 'node16'
  main: 'dist/index.js'
  post: 'dist/index.js'
