name: Acorn Login
description: Logs in to an Acorn registry
author: 'Acorn Labs, Inc.'
inputs:
  registry:
    description: 'Registry server address'
    default: ahcr.io
    required: false
  username:
    description: 'Username'
    required: true
  password:
    description: Password
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
  post: 'dist/index.js'
